/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as IptvRouteImport } from './routes/iptv'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as AdminArenaRouteImport } from './routes/admin.arena'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminIptvBlocksRouteImport } from './routes/admin.iptv-blocks'
import { Route as AdminIptvProviderRouteImport } from './routes/admin.iptv-provider'
import { Route as AdminIptvRejectionsRouteImport } from './routes/admin.iptv-rejections'
import { Route as AdminLoungesRouteImport } from './routes/admin.lounges'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminQuickDaresRouteImport } from './routes/admin.quick-dares'
import { Route as AdminSegMetricsRouteImport } from './routes/admin.seg-metrics'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSiteSettingsRouteImport } from './routes/admin.site-settings'
import { Route as AdminTipsRouteImport } from './routes/admin.tips'
import { Route as AdminTopupHistoryRouteImport } from './routes/admin.topup-history'
import { Route as AdminTopupsRouteImport } from './routes/admin.topups'
import { Route as AdminTvsRouteImport } from './routes/admin.tvs'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWalletLedgerRouteImport } from './routes/admin.wallet-ledger'
import { Route as ArenaIndexRouteImport } from './routes/arena.index'
import { Route as ArenaMatchIdRouteImport } from './routes/arena.$matchId'
import { Route as DevMotionTestRouteImport } from './routes/dev.motion-test'
import { Route as DevTilethumbRouteImport } from './routes/dev.tilethumb'
import { Route as IptvIndexRouteImport } from './routes/iptv.index'
import { Route as IptvChannelIdRouteImport } from './routes/iptv.$channelId'
import { Route as IptvSettingsRouteImport } from './routes/iptv.settings'
import { Route as LoungeLoungeIdRouteImport } from './routes/lounge.$loungeId'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as EmbedLoungeLoungeIdRouteImport } from './routes/embed.lounge.$loungeId'
import { Route as ApiPublicHooksHealthCheckRouteImport } from './routes/api/public/hooks/health-check'
import { Route as ApiPublicIptvPlaylistRouteImport } from './routes/api/public/iptv/playlist'
import { Route as ApiPublicIptvProxyMetricsRouteImport } from './routes/api/public/iptv/proxy-metrics'
import { Route as ApiPublicIptvStreamRouteImport } from './routes/api/public/iptv/stream'
import { Route as ApiSportsArenaTvTvIdPlaylistRouteImport } from './routes/api/sports-arena/tv.$tvId.playlist'
import { Route as ApiSportsArenaTvTvIdSegRouteImport } from './routes/api/sports-arena/tv.$tvId.seg'
import { Route as ApiPublicIptvChannelChannelIdPlaylistRouteImport } from './routes/api/public/iptv/channel.$channelId.playlist'
import { Route as ApiPublicIptvChannelChannelIdSegmentRouteImport } from './routes/api/public/iptv/channel.$channelId.segment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const IptvRoute = IptvRouteImport.update({
  id: '/iptv',
  path: '/iptv',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArenaRoute = AdminArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIptvBlocksRoute = AdminIptvBlocksRouteImport.update({
  id: '/iptv-blocks',
  path: '/iptv-blocks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIptvProviderRoute = AdminIptvProviderRouteImport.update({
  id: '/iptv-provider',
  path: '/iptv-provider',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIptvRejectionsRoute = AdminIptvRejectionsRouteImport.update({
  id: '/iptv-rejections',
  path: '/iptv-rejections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoungesRoute = AdminLoungesRouteImport.update({
  id: '/lounges',
  path: '/lounges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuickDaresRoute = AdminQuickDaresRouteImport.update({
  id: '/quick-dares',
  path: '/quick-dares',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSegMetricsRoute = AdminSegMetricsRouteImport.update({
  id: '/seg-metrics',
  path: '/seg-metrics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteSettingsRoute = AdminSiteSettingsRouteImport.update({
  id: '/site-settings',
  path: '/site-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTipsRoute = AdminTipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTopupHistoryRoute = AdminTopupHistoryRouteImport.update({
  id: '/topup-history',
  path: '/topup-history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTopupsRoute = AdminTopupsRouteImport.update({
  id: '/topups',
  path: '/topups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTvsRoute = AdminTvsRouteImport.update({
  id: '/tvs',
  path: '/tvs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletLedgerRoute = AdminWalletLedgerRouteImport.update({
  id: '/wallet-ledger',
  path: '/wallet-ledger',
  getParentRoute: () => AdminRoute,
} as any)
const ArenaIndexRoute = ArenaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArenaRoute,
} as any)
const ArenaMatchIdRoute = ArenaMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => ArenaRoute,
} as any)
const DevMotionTestRoute = DevMotionTestRouteImport.update({
  id: '/dev/motion-test',
  path: '/dev/motion-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DevTilethumbRoute = DevTilethumbRouteImport.update({
  id: '/dev/tilethumb',
  path: '/dev/tilethumb',
  getParentRoute: () => rootRouteImport,
} as any)
const IptvIndexRoute = IptvIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IptvRoute,
} as any)
const IptvChannelIdRoute = IptvChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => IptvRoute,
} as any)
const IptvSettingsRoute = IptvSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => IptvRoute,
} as any)
const LoungeLoungeIdRoute = LoungeLoungeIdRouteImport.update({
  id: '/lounge/$loungeId',
  path: '/lounge/$loungeId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmbedLoungeLoungeIdRoute = EmbedLoungeLoungeIdRouteImport.update({
  id: '/embed/lounge/$loungeId',
  path: '/embed/lounge/$loungeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksHealthCheckRoute =
  ApiPublicHooksHealthCheckRouteImport.update({
    id: '/api/public/hooks/health-check',
    path: '/api/public/hooks/health-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIptvPlaylistRoute = ApiPublicIptvPlaylistRouteImport.update({
  id: '/api/public/iptv/playlist',
  path: '/api/public/iptv/playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIptvProxyMetricsRoute =
  ApiPublicIptvProxyMetricsRouteImport.update({
    id: '/api/public/iptv/proxy-metrics',
    path: '/api/public/iptv/proxy-metrics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIptvStreamRoute = ApiPublicIptvStreamRouteImport.update({
  id: '/api/public/iptv/stream',
  path: '/api/public/iptv/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSportsArenaTvTvIdPlaylistRoute =
  ApiSportsArenaTvTvIdPlaylistRouteImport.update({
    id: '/api/sports-arena/tv/$tvId/playlist',
    path: '/api/sports-arena/tv/$tvId/playlist',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSportsArenaTvTvIdSegRoute = ApiSportsArenaTvTvIdSegRouteImport.update({
  id: '/api/sports-arena/tv/$tvId/seg',
  path: '/api/sports-arena/tv/$tvId/seg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIptvChannelChannelIdPlaylistRoute =
  ApiPublicIptvChannelChannelIdPlaylistRouteImport.update({
    id: '/api/public/iptv/channel/$channelId/playlist',
    path: '/api/public/iptv/channel/$channelId/playlist',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIptvChannelChannelIdSegmentRoute =
  ApiPublicIptvChannelChannelIdSegmentRouteImport.update({
    id: '/api/public/iptv/channel/$channelId/segment',
    path: '/api/public/iptv/channel/$channelId/segment',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/arena': typeof ArenaRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/iptv': typeof IptvRouteWithChildren
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/arena': typeof AdminArenaRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/iptv-blocks': typeof AdminIptvBlocksRoute
  '/admin/iptv-provider': typeof AdminIptvProviderRoute
  '/admin/iptv-rejections': typeof AdminIptvRejectionsRoute
  '/admin/lounges': typeof AdminLoungesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/quick-dares': typeof AdminQuickDaresRoute
  '/admin/seg-metrics': typeof AdminSegMetricsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/tips': typeof AdminTipsRoute
  '/admin/topup-history': typeof AdminTopupHistoryRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/tvs': typeof AdminTvsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet-ledger': typeof AdminWalletLedgerRoute
  '/arena/$matchId': typeof ArenaMatchIdRoute
  '/dev/motion-test': typeof DevMotionTestRoute
  '/dev/tilethumb': typeof DevTilethumbRoute
  '/iptv/$channelId': typeof IptvChannelIdRoute
  '/iptv/settings': typeof IptvSettingsRoute
  '/lounge/$loungeId': typeof LoungeLoungeIdRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/arena/': typeof ArenaIndexRoute
  '/iptv/': typeof IptvIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/embed/lounge/$loungeId': typeof EmbedLoungeLoungeIdRoute
  '/api/public/hooks/health-check': typeof ApiPublicHooksHealthCheckRoute
  '/api/public/iptv/playlist': typeof ApiPublicIptvPlaylistRoute
  '/api/public/iptv/proxy-metrics': typeof ApiPublicIptvProxyMetricsRoute
  '/api/public/iptv/stream': typeof ApiPublicIptvStreamRoute
  '/api/sports-arena/tv/$tvId/playlist': typeof ApiSportsArenaTvTvIdPlaylistRoute
  '/api/sports-arena/tv/$tvId/seg': typeof ApiSportsArenaTvTvIdSegRoute
  '/api/public/iptv/channel/$channelId/playlist': typeof ApiPublicIptvChannelChannelIdPlaylistRoute
  '/api/public/iptv/channel/$channelId/segment': typeof ApiPublicIptvChannelChannelIdSegmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/arena': typeof AdminArenaRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/iptv-blocks': typeof AdminIptvBlocksRoute
  '/admin/iptv-provider': typeof AdminIptvProviderRoute
  '/admin/iptv-rejections': typeof AdminIptvRejectionsRoute
  '/admin/lounges': typeof AdminLoungesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/quick-dares': typeof AdminQuickDaresRoute
  '/admin/seg-metrics': typeof AdminSegMetricsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/tips': typeof AdminTipsRoute
  '/admin/topup-history': typeof AdminTopupHistoryRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/tvs': typeof AdminTvsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet-ledger': typeof AdminWalletLedgerRoute
  '/arena/$matchId': typeof ArenaMatchIdRoute
  '/dev/motion-test': typeof DevMotionTestRoute
  '/dev/tilethumb': typeof DevTilethumbRoute
  '/iptv/$channelId': typeof IptvChannelIdRoute
  '/iptv/settings': typeof IptvSettingsRoute
  '/lounge/$loungeId': typeof LoungeLoungeIdRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/arena': typeof ArenaIndexRoute
  '/iptv': typeof IptvIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/embed/lounge/$loungeId': typeof EmbedLoungeLoungeIdRoute
  '/api/public/hooks/health-check': typeof ApiPublicHooksHealthCheckRoute
  '/api/public/iptv/playlist': typeof ApiPublicIptvPlaylistRoute
  '/api/public/iptv/proxy-metrics': typeof ApiPublicIptvProxyMetricsRoute
  '/api/public/iptv/stream': typeof ApiPublicIptvStreamRoute
  '/api/sports-arena/tv/$tvId/playlist': typeof ApiSportsArenaTvTvIdPlaylistRoute
  '/api/sports-arena/tv/$tvId/seg': typeof ApiSportsArenaTvTvIdSegRoute
  '/api/public/iptv/channel/$channelId/playlist': typeof ApiPublicIptvChannelChannelIdPlaylistRoute
  '/api/public/iptv/channel/$channelId/segment': typeof ApiPublicIptvChannelChannelIdSegmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/arena': typeof ArenaRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/iptv': typeof IptvRouteWithChildren
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/arena': typeof AdminArenaRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/iptv-blocks': typeof AdminIptvBlocksRoute
  '/admin/iptv-provider': typeof AdminIptvProviderRoute
  '/admin/iptv-rejections': typeof AdminIptvRejectionsRoute
  '/admin/lounges': typeof AdminLoungesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/quick-dares': typeof AdminQuickDaresRoute
  '/admin/seg-metrics': typeof AdminSegMetricsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/tips': typeof AdminTipsRoute
  '/admin/topup-history': typeof AdminTopupHistoryRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/tvs': typeof AdminTvsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet-ledger': typeof AdminWalletLedgerRoute
  '/arena/$matchId': typeof ArenaMatchIdRoute
  '/dev/motion-test': typeof DevMotionTestRoute
  '/dev/tilethumb': typeof DevTilethumbRoute
  '/iptv/$channelId': typeof IptvChannelIdRoute
  '/iptv/settings': typeof IptvSettingsRoute
  '/lounge/$loungeId': typeof LoungeLoungeIdRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/arena/': typeof ArenaIndexRoute
  '/iptv/': typeof IptvIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/embed/lounge/$loungeId': typeof EmbedLoungeLoungeIdRoute
  '/api/public/hooks/health-check': typeof ApiPublicHooksHealthCheckRoute
  '/api/public/iptv/playlist': typeof ApiPublicIptvPlaylistRoute
  '/api/public/iptv/proxy-metrics': typeof ApiPublicIptvProxyMetricsRoute
  '/api/public/iptv/stream': typeof ApiPublicIptvStreamRoute
  '/api/sports-arena/tv/$tvId/playlist': typeof ApiSportsArenaTvTvIdPlaylistRoute
  '/api/sports-arena/tv/$tvId/seg': typeof ApiSportsArenaTvTvIdSegRoute
  '/api/public/iptv/channel/$channelId/playlist': typeof ApiPublicIptvChannelChannelIdPlaylistRoute
  '/api/public/iptv/channel/$channelId/segment': typeof ApiPublicIptvChannelChannelIdSegmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arena'
    | '/auth'
    | '/dashboard'
    | '/forbidden'
    | '/forgot-password'
    | '/friends'
    | '/iptv'
    | '/mcp'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/wallet'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ads'
    | '/admin/arena'
    | '/admin/audit'
    | '/admin/health'
    | '/admin/iptv-blocks'
    | '/admin/iptv-provider'
    | '/admin/iptv-rejections'
    | '/admin/lounges'
    | '/admin/payments'
    | '/admin/quick-dares'
    | '/admin/seg-metrics'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/admin/tips'
    | '/admin/topup-history'
    | '/admin/topups'
    | '/admin/tvs'
    | '/admin/users'
    | '/admin/wallet-ledger'
    | '/arena/$matchId'
    | '/dev/motion-test'
    | '/dev/tilethumb'
    | '/iptv/$channelId'
    | '/iptv/settings'
    | '/lounge/$loungeId'
    | '/matches/$matchId'
    | '/arena/'
    | '/iptv/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/embed/lounge/$loungeId'
    | '/api/public/hooks/health-check'
    | '/api/public/iptv/playlist'
    | '/api/public/iptv/proxy-metrics'
    | '/api/public/iptv/stream'
    | '/api/sports-arena/tv/$tvId/playlist'
    | '/api/sports-arena/tv/$tvId/seg'
    | '/api/public/iptv/channel/$channelId/playlist'
    | '/api/public/iptv/channel/$channelId/segment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/forbidden'
    | '/forgot-password'
    | '/friends'
    | '/mcp'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/wallet'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ads'
    | '/admin/arena'
    | '/admin/audit'
    | '/admin/health'
    | '/admin/iptv-blocks'
    | '/admin/iptv-provider'
    | '/admin/iptv-rejections'
    | '/admin/lounges'
    | '/admin/payments'
    | '/admin/quick-dares'
    | '/admin/seg-metrics'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/admin/tips'
    | '/admin/topup-history'
    | '/admin/topups'
    | '/admin/tvs'
    | '/admin/users'
    | '/admin/wallet-ledger'
    | '/arena/$matchId'
    | '/dev/motion-test'
    | '/dev/tilethumb'
    | '/iptv/$channelId'
    | '/iptv/settings'
    | '/lounge/$loungeId'
    | '/matches/$matchId'
    | '/arena'
    | '/iptv'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/embed/lounge/$loungeId'
    | '/api/public/hooks/health-check'
    | '/api/public/iptv/playlist'
    | '/api/public/iptv/proxy-metrics'
    | '/api/public/iptv/stream'
    | '/api/sports-arena/tv/$tvId/playlist'
    | '/api/sports-arena/tv/$tvId/seg'
    | '/api/public/iptv/channel/$channelId/playlist'
    | '/api/public/iptv/channel/$channelId/segment'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arena'
    | '/auth'
    | '/dashboard'
    | '/forbidden'
    | '/forgot-password'
    | '/friends'
    | '/iptv'
    | '/mcp'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/wallet'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ads'
    | '/admin/arena'
    | '/admin/audit'
    | '/admin/health'
    | '/admin/iptv-blocks'
    | '/admin/iptv-provider'
    | '/admin/iptv-rejections'
    | '/admin/lounges'
    | '/admin/payments'
    | '/admin/quick-dares'
    | '/admin/seg-metrics'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/admin/tips'
    | '/admin/topup-history'
    | '/admin/topups'
    | '/admin/tvs'
    | '/admin/users'
    | '/admin/wallet-ledger'
    | '/arena/$matchId'
    | '/dev/motion-test'
    | '/dev/tilethumb'
    | '/iptv/$channelId'
    | '/iptv/settings'
    | '/lounge/$loungeId'
    | '/matches/$matchId'
    | '/arena/'
    | '/iptv/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/embed/lounge/$loungeId'
    | '/api/public/hooks/health-check'
    | '/api/public/iptv/playlist'
    | '/api/public/iptv/proxy-metrics'
    | '/api/public/iptv/stream'
    | '/api/sports-arena/tv/$tvId/playlist'
    | '/api/sports-arena/tv/$tvId/seg'
    | '/api/public/iptv/channel/$channelId/playlist'
    | '/api/public/iptv/channel/$channelId/segment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArenaRoute: typeof ArenaRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ForbiddenRoute: typeof ForbiddenRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FriendsRoute: typeof FriendsRoute
  IptvRoute: typeof IptvRouteWithChildren
  McpRoute: typeof McpRoute
  MessagesRoute: typeof MessagesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DevMotionTestRoute: typeof DevMotionTestRoute
  DevTilethumbRoute: typeof DevTilethumbRoute
  LoungeLoungeIdRoute: typeof LoungeLoungeIdRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  EmbedLoungeLoungeIdRoute: typeof EmbedLoungeLoungeIdRoute
  ApiPublicHooksHealthCheckRoute: typeof ApiPublicHooksHealthCheckRoute
  ApiPublicIptvPlaylistRoute: typeof ApiPublicIptvPlaylistRoute
  ApiPublicIptvProxyMetricsRoute: typeof ApiPublicIptvProxyMetricsRoute
  ApiPublicIptvStreamRoute: typeof ApiPublicIptvStreamRoute
  ApiSportsArenaTvTvIdPlaylistRoute: typeof ApiSportsArenaTvTvIdPlaylistRoute
  ApiSportsArenaTvTvIdSegRoute: typeof ApiSportsArenaTvTvIdSegRoute
  ApiPublicIptvChannelChannelIdPlaylistRoute: typeof ApiPublicIptvChannelChannelIdPlaylistRoute
  ApiPublicIptvChannelChannelIdSegmentRoute: typeof ApiPublicIptvChannelChannelIdSegmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iptv': {
      id: '/iptv'
      path: '/iptv'
      fullPath: '/iptv'
      preLoaderRoute: typeof IptvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/arena': {
      id: '/admin/arena'
      path: '/arena'
      fullPath: '/admin/arena'
      preLoaderRoute: typeof AdminArenaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/iptv-blocks': {
      id: '/admin/iptv-blocks'
      path: '/iptv-blocks'
      fullPath: '/admin/iptv-blocks'
      preLoaderRoute: typeof AdminIptvBlocksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/iptv-provider': {
      id: '/admin/iptv-provider'
      path: '/iptv-provider'
      fullPath: '/admin/iptv-provider'
      preLoaderRoute: typeof AdminIptvProviderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/iptv-rejections': {
      id: '/admin/iptv-rejections'
      path: '/iptv-rejections'
      fullPath: '/admin/iptv-rejections'
      preLoaderRoute: typeof AdminIptvRejectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lounges': {
      id: '/admin/lounges'
      path: '/lounges'
      fullPath: '/admin/lounges'
      preLoaderRoute: typeof AdminLoungesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quick-dares': {
      id: '/admin/quick-dares'
      path: '/quick-dares'
      fullPath: '/admin/quick-dares'
      preLoaderRoute: typeof AdminQuickDaresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seg-metrics': {
      id: '/admin/seg-metrics'
      path: '/seg-metrics'
      fullPath: '/admin/seg-metrics'
      preLoaderRoute: typeof AdminSegMetricsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site-settings': {
      id: '/admin/site-settings'
      path: '/site-settings'
      fullPath: '/admin/site-settings'
      preLoaderRoute: typeof AdminSiteSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tips': {
      id: '/admin/tips'
      path: '/tips'
      fullPath: '/admin/tips'
      preLoaderRoute: typeof AdminTipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/topup-history': {
      id: '/admin/topup-history'
      path: '/topup-history'
      fullPath: '/admin/topup-history'
      preLoaderRoute: typeof AdminTopupHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/topups': {
      id: '/admin/topups'
      path: '/topups'
      fullPath: '/admin/topups'
      preLoaderRoute: typeof AdminTopupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tvs': {
      id: '/admin/tvs'
      path: '/tvs'
      fullPath: '/admin/tvs'
      preLoaderRoute: typeof AdminTvsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallet-ledger': {
      id: '/admin/wallet-ledger'
      path: '/wallet-ledger'
      fullPath: '/admin/wallet-ledger'
      preLoaderRoute: typeof AdminWalletLedgerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/arena/': {
      id: '/arena/'
      path: '/'
      fullPath: '/arena/'
      preLoaderRoute: typeof ArenaIndexRouteImport
      parentRoute: typeof ArenaRoute
    }
    '/arena/$matchId': {
      id: '/arena/$matchId'
      path: '/$matchId'
      fullPath: '/arena/$matchId'
      preLoaderRoute: typeof ArenaMatchIdRouteImport
      parentRoute: typeof ArenaRoute
    }
    '/dev/motion-test': {
      id: '/dev/motion-test'
      path: '/dev/motion-test'
      fullPath: '/dev/motion-test'
      preLoaderRoute: typeof DevMotionTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/tilethumb': {
      id: '/dev/tilethumb'
      path: '/dev/tilethumb'
      fullPath: '/dev/tilethumb'
      preLoaderRoute: typeof DevTilethumbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iptv/': {
      id: '/iptv/'
      path: '/'
      fullPath: '/iptv/'
      preLoaderRoute: typeof IptvIndexRouteImport
      parentRoute: typeof IptvRoute
    }
    '/iptv/$channelId': {
      id: '/iptv/$channelId'
      path: '/$channelId'
      fullPath: '/iptv/$channelId'
      preLoaderRoute: typeof IptvChannelIdRouteImport
      parentRoute: typeof IptvRoute
    }
    '/iptv/settings': {
      id: '/iptv/settings'
      path: '/settings'
      fullPath: '/iptv/settings'
      preLoaderRoute: typeof IptvSettingsRouteImport
      parentRoute: typeof IptvRoute
    }
    '/lounge/$loungeId': {
      id: '/lounge/$loungeId'
      path: '/lounge/$loungeId'
      fullPath: '/lounge/$loungeId'
      preLoaderRoute: typeof LoungeLoungeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/lounge/$loungeId': {
      id: '/embed/lounge/$loungeId'
      path: '/embed/lounge/$loungeId'
      fullPath: '/embed/lounge/$loungeId'
      preLoaderRoute: typeof EmbedLoungeLoungeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/health-check': {
      id: '/api/public/hooks/health-check'
      path: '/api/public/hooks/health-check'
      fullPath: '/api/public/hooks/health-check'
      preLoaderRoute: typeof ApiPublicHooksHealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/iptv/playlist': {
      id: '/api/public/iptv/playlist'
      path: '/api/public/iptv/playlist'
      fullPath: '/api/public/iptv/playlist'
      preLoaderRoute: typeof ApiPublicIptvPlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/iptv/proxy-metrics': {
      id: '/api/public/iptv/proxy-metrics'
      path: '/api/public/iptv/proxy-metrics'
      fullPath: '/api/public/iptv/proxy-metrics'
      preLoaderRoute: typeof ApiPublicIptvProxyMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/iptv/stream': {
      id: '/api/public/iptv/stream'
      path: '/api/public/iptv/stream'
      fullPath: '/api/public/iptv/stream'
      preLoaderRoute: typeof ApiPublicIptvStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sports-arena/tv/$tvId/playlist': {
      id: '/api/sports-arena/tv/$tvId/playlist'
      path: '/api/sports-arena/tv/$tvId/playlist'
      fullPath: '/api/sports-arena/tv/$tvId/playlist'
      preLoaderRoute: typeof ApiSportsArenaTvTvIdPlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sports-arena/tv/$tvId/seg': {
      id: '/api/sports-arena/tv/$tvId/seg'
      path: '/api/sports-arena/tv/$tvId/seg'
      fullPath: '/api/sports-arena/tv/$tvId/seg'
      preLoaderRoute: typeof ApiSportsArenaTvTvIdSegRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/iptv/channel/$channelId/playlist': {
      id: '/api/public/iptv/channel/$channelId/playlist'
      path: '/api/public/iptv/channel/$channelId/playlist'
      fullPath: '/api/public/iptv/channel/$channelId/playlist'
      preLoaderRoute: typeof ApiPublicIptvChannelChannelIdPlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/iptv/channel/$channelId/segment': {
      id: '/api/public/iptv/channel/$channelId/segment'
      path: '/api/public/iptv/channel/$channelId/segment'
      fullPath: '/api/public/iptv/channel/$channelId/segment'
      preLoaderRoute: typeof ApiPublicIptvChannelChannelIdSegmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminArenaRoute: typeof AdminArenaRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminIptvBlocksRoute: typeof AdminIptvBlocksRoute
  AdminIptvProviderRoute: typeof AdminIptvProviderRoute
  AdminIptvRejectionsRoute: typeof AdminIptvRejectionsRoute
  AdminLoungesRoute: typeof AdminLoungesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminQuickDaresRoute: typeof AdminQuickDaresRoute
  AdminSegMetricsRoute: typeof AdminSegMetricsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSiteSettingsRoute: typeof AdminSiteSettingsRoute
  AdminTipsRoute: typeof AdminTipsRoute
  AdminTopupHistoryRoute: typeof AdminTopupHistoryRoute
  AdminTopupsRoute: typeof AdminTopupsRoute
  AdminTvsRoute: typeof AdminTvsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletLedgerRoute: typeof AdminWalletLedgerRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminArenaRoute: AdminArenaRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminIptvBlocksRoute: AdminIptvBlocksRoute,
  AdminIptvProviderRoute: AdminIptvProviderRoute,
  AdminIptvRejectionsRoute: AdminIptvRejectionsRoute,
  AdminLoungesRoute: AdminLoungesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminQuickDaresRoute: AdminQuickDaresRoute,
  AdminSegMetricsRoute: AdminSegMetricsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSiteSettingsRoute: AdminSiteSettingsRoute,
  AdminTipsRoute: AdminTipsRoute,
  AdminTopupHistoryRoute: AdminTopupHistoryRoute,
  AdminTopupsRoute: AdminTopupsRoute,
  AdminTvsRoute: AdminTvsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletLedgerRoute: AdminWalletLedgerRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArenaRouteChildren {
  ArenaMatchIdRoute: typeof ArenaMatchIdRoute
  ArenaIndexRoute: typeof ArenaIndexRoute
}

const ArenaRouteChildren: ArenaRouteChildren = {
  ArenaMatchIdRoute: ArenaMatchIdRoute,
  ArenaIndexRoute: ArenaIndexRoute,
}

const ArenaRouteWithChildren = ArenaRoute._addFileChildren(ArenaRouteChildren)

interface IptvRouteChildren {
  IptvChannelIdRoute: typeof IptvChannelIdRoute
  IptvSettingsRoute: typeof IptvSettingsRoute
  IptvIndexRoute: typeof IptvIndexRoute
}

const IptvRouteChildren: IptvRouteChildren = {
  IptvChannelIdRoute: IptvChannelIdRoute,
  IptvSettingsRoute: IptvSettingsRoute,
  IptvIndexRoute: IptvIndexRoute,
}

const IptvRouteWithChildren = IptvRoute._addFileChildren(IptvRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArenaRoute: ArenaRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ForbiddenRoute: ForbiddenRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FriendsRoute: FriendsRoute,
  IptvRoute: IptvRouteWithChildren,
  McpRoute: McpRoute,
  MessagesRoute: MessagesRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DevMotionTestRoute: DevMotionTestRoute,
  DevTilethumbRoute: DevTilethumbRoute,
  LoungeLoungeIdRoute: LoungeLoungeIdRoute,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  EmbedLoungeLoungeIdRoute: EmbedLoungeLoungeIdRoute,
  ApiPublicHooksHealthCheckRoute: ApiPublicHooksHealthCheckRoute,
  ApiPublicIptvPlaylistRoute: ApiPublicIptvPlaylistRoute,
  ApiPublicIptvProxyMetricsRoute: ApiPublicIptvProxyMetricsRoute,
  ApiPublicIptvStreamRoute: ApiPublicIptvStreamRoute,
  ApiSportsArenaTvTvIdPlaylistRoute: ApiSportsArenaTvTvIdPlaylistRoute,
  ApiSportsArenaTvTvIdSegRoute: ApiSportsArenaTvTvIdSegRoute,
  ApiPublicIptvChannelChannelIdPlaylistRoute:
    ApiPublicIptvChannelChannelIdPlaylistRoute,
  ApiPublicIptvChannelChannelIdSegmentRoute:
    ApiPublicIptvChannelChannelIdSegmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
